version: "3.9"
services:
  app:
    build: ./ao-app
  nginx:
    image: nginx:alpine
    hostname: 'nginx-lb'
    volumes:
      - ./nginx-lb/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    ports:
      - "4000:4000"
    restart: always